apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-based-sample-app-deployment
  labels:
    app: tweet-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tweet-app
  template:
    metadata:
      name: nginx-based-sample-app-pod
      labels:
        app: tweet-app
    spec:
      containers:
      - name: tweet-pod
        image: rajbhaveshraj/devopstest:tweetappV1
        ports:
         - containerPort: 80
